options {
    directory "/var/cache/bind";
    listen-on port 53 { any; };
    listen-on-v6 port 53 { none; };
    allow-query { any; };
    recursion no;
    dnssec-validation no;
};

zone "lab.3ss.local" {
    type master;
    file "/etc/bind/zones/lab.3ss.local.zone";
};
